name = "portfolio-setyorini"
compatibility_date = "2025-05-23"
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "GALLERY_KV"
id = "GANTI_DENGAN_NAMESPACE_ID_DARI_DASHBOARD"
