name = "portfolio-setyorini"
compatibility_date = "2025-05-23"
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "gallery-kv"
id = "d13cf5ddf65c407ea9e77bb1c9d3d5e6"
